[[cozip]]
arch = "aarch64"
os = "linux"
libc = "glibc"
git-tree-sha1 = "125e47b7107e09f8f72ced20de8600c01d5bc9d6"
lazy = true

    [[cozip.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/v2026.5.11/libcozip-2026.5.11-linux-aarch64.tar.gz"
    sha256 = "fe052b5be5337b201ba9e5f77ca641fc372981125ba9c815c481c84404f51f94"

[[cozip]]
arch = "x86_64"
os = "linux"
libc = "glibc"
git-tree-sha1 = "e12bb5eee2a2f0e5d1134204e03c8c4d2730a1b6"
lazy = true

    [[cozip.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/v2026.5.11/libcozip-2026.5.11-linux-x86_64.tar.gz"
    sha256 = "d41bf089d8aaf8495992b18daa7f5f150ffacc2f94a8f8e716cd9add8a1fcf08"

[[cozip]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "9c57dc17edcb8041ffafde6b45f50c62e0e43eef"
lazy = true

    [[cozip.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/v2026.5.11/libcozip-2026.5.11-macos-universal.tar.gz"
    sha256 = "52e2a94cb57283cd438a2715cc82a1e7563a5165ca0ac22bf1bfab49e44ea5ee"

[[cozip]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "9c57dc17edcb8041ffafde6b45f50c62e0e43eef"
lazy = true

    [[cozip.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/v2026.5.11/libcozip-2026.5.11-macos-universal.tar.gz"
    sha256 = "52e2a94cb57283cd438a2715cc82a1e7563a5165ca0ac22bf1bfab49e44ea5ee"

[[cozip]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "8ec310c39ba9f61e54395b41730569a72b4a2027"
lazy = true

    [[cozip.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/v2026.5.11/libcozip-2026.5.11-windows-x86_64.tar.gz"
    sha256 = "48e4c18830bcfaf33f31d0852e5ba910a46b8595d3b4c4a81c51bd123923e49f"

