[[taco]]
arch = "aarch64"
os = "linux"
libc = "glibc"
git-tree-sha1 = "c38d5a875549798b5d73136ed628f22f2e5303a3"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.11.0/libtaco-0.11.0-linux-aarch64.tar.gz"
    sha256 = "4669b9a94654d18c9ee180dd462be339e26135e8d004eed4ce1be81945bab78b"

[[taco]]
arch = "x86_64"
os = "linux"
libc = "glibc"
git-tree-sha1 = "ed49e8b0595e9f7bef23c7069682ca1ed64e0827"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.11.0/libtaco-0.11.0-linux-x86_64.tar.gz"
    sha256 = "54f9e203d1e13285cf7297e1f2d53e76212cb00c3fa05e278c1482c3e2fce274"

[[taco]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "cbcdc2d2e562d7f97a11e61181fa925159e3c72e"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.11.0/libtaco-0.11.0-macos-aarch64.tar.gz"
    sha256 = "ceba6623392261889d53c73aabb72421cef34a6ca274316ccd8087e87d3c05d0"

[[taco]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "822103efe673878a49b82d734bf278ce4f02761b"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.11.0/libtaco-0.11.0-macos-x86_64.tar.gz"
    sha256 = "f027b85033605fa14e939fec04dadbdac09a98e47c8aef75ba2a6bf6fe9da4ce"

[[taco]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "bb53520c926674b61bedfdf50d20b8150f99ea7e"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.11.0/libtaco-0.11.0-windows-x86_64.tar.gz"
    sha256 = "c51aee12c72534812bcc8198f94470f505ba74fb8343b607aa4987944542068d"

