[[taco]]
arch = "aarch64"
os = "linux"
libc = "glibc"
git-tree-sha1 = "935c8ba4cf19e7eb4212a2e2c453dc82483b504b"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.9.1/libtaco-0.9.1-linux-aarch64.tar.gz"
    sha256 = "9dc19cad623db8331db6dba4b8e774b8fbf13e1fd8090209c5048e2b66d9316b"

[[taco]]
arch = "x86_64"
os = "linux"
libc = "glibc"
git-tree-sha1 = "077bdbd2b5a28e3a284369066fb7a555db3f1000"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.9.1/libtaco-0.9.1-linux-x86_64.tar.gz"
    sha256 = "64f0a713383da4d47ee2414d7dd346a9b4aca1d15d3fd136dd3864fe5f36bdc6"

[[taco]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "a5ea978e521cd9bc17f99c22abb9b8ff17329485"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.9.1/libtaco-0.9.1-macos-aarch64.tar.gz"
    sha256 = "73e3cfe20debf1040a48d4fee5a6ecef6c160b4094a7a91fd5dfa5b7ead34263"

[[taco]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "231efaf7fc21242e55e03159d7a0f29431291f21"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.9.1/libtaco-0.9.1-macos-x86_64.tar.gz"
    sha256 = "14278c5ea833f41cbb5f11d3a3b7ba5ec684bb6fff5be72fece02529e793dcb1"

[[taco]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "1937edb7539e903766c4289e0234fff647d539c0"
lazy = true

    [[taco.download]]
    url = "https://github.com/asterisk-labs/taco/releases/download/libtaco-v0.9.1/libtaco-0.9.1-windows-x86_64.tar.gz"
    sha256 = "e302374854ce31afb569ad5bfec5b8c77205c3c6a04abee6ad19bedeb35c7b01"

