from __future__ import annotations

import json
from typing import Any

import pyarrow as pa

from ..errors import ContainerError
from . import native
from .collection import load_collection
from .query import Files, Index, build_native_sql
from .source import PathInput

_QUERIES = {"collection", "contract", "levels", "native_sql", "profile", "structure"}


def contract(path: PathInput) -> pa.Table:
    """Return the contract as rows of ``kind`` and ``value``."""
    dataset = native.NativeDataset(path)
    rows = [("structure", item) for item in dataset.structure]
    rows += [("level", level) for level in dataset.levels]
    if dataset.derived is not None:
        rows.append(("derived", dataset.derived))
    return pa.table(
        {
            "kind": pa.array([kind for kind, _ in rows], pa.string()),
            "value": pa.array([value for _, value in rows], pa.string()),
        }
    )


def structure(path: PathInput) -> list[str]:
    """Return the declared ``taco:structure`` paths."""
    return native.NativeDataset(path).structure


def levels(path: PathInput) -> list[str]:
    """Return metadata levels, parents before children."""
    return native.NativeDataset(path).levels


def derived(path: PathInput) -> dict[str, Any]:
    """Return serialized ``taco:derived`` declarations."""
    value = native.NativeDataset(path).derived
    if value is None:
        return {}
    data = json.loads(value)
    if not isinstance(data, dict):
        raise ContainerError(f"taco:derived is not a JSON object: {path}")
    return data


def collection(path: PathInput) -> dict[str, object]:
    """Return parsed ``COLLECTION.json`` metadata."""
    return load_collection(path)


def profile(path: PathInput) -> str:
    """Return the CoZIP profile: ``none``, ``flat`` or ``taco``."""
    return native.profile(path)


def native_sql(
    path: PathInput,
    *,
    idx: Index = None,
    level: str | None = None,
    layout: str = "wide",
    files: Files = None,
    location: bool = True,
) -> str:
    """Return a low-level query generated by the native core for debugging."""
    if layout not in ("wide", "long"):
        raise ValueError("layout must be 'wide' or 'long'")
    return build_native_sql(path, idx=idx, level=level, pivoted=layout == "wide", files=files, location=location)


def inspect(path: PathInput, query: str) -> object:
    """Inspect one part of a dataset without reading its samples."""
    if not isinstance(query, str) or query not in _QUERIES:
        choices = ", ".join(sorted(_QUERIES))
        raise ValueError(f"query must be one of: {choices}")
    operation = globals()[query]
    return operation(path)


__all__ = ["collection", "contract", "derived", "inspect", "levels", "native_sql", "profile", "structure"]
